"""init_runs_events

Revision ID: 628737b42193
Revises: 
Create Date: 2026-02-28 09:30:36.046176
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628737b42193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'runs',
        sa.Column('run_id', sa.String(length=64), nullable=False),
        sa.Column('mode', sa.String(length=16), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('idempotency_key', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.Column('error', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('run_id'),
        sa.UniqueConstraint('idempotency_key', name='uq_runs_idempotency_key'),
    )
    op.create_table(
        'events',
        sa.Column('event_id', sa.String(length=64), nullable=False),
        sa.Column('source', sa.String(length=32), nullable=False),
        sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('payload_ref', sa.String(length=512), nullable=False),
        sa.Column('normalized_ref', sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint('event_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('runs')
    # ### end Alembic commands ###
